### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by DelphinPETER**

### CODE REVIEW

**Comment by koush** [comment]
This should go onto gerrit, is it not up there yet? Ping @ctso

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by ciwrl** [comment]
@koush The pull requests for these translations are per @ctso's request

Edit: I'm mistaken, that was for the CMAccount app. Will inform Translator community.

**Comment by ctso** [comment]
Pull requests for this project must be submitted through Gerrit.

**Pull request closed without merging**
